### ISSUE TITLE
lOGO OFFER FOR CLASSINJECTOR

### ISSUE THREAD

**Issue by familqasimov** [tmurakami/classinjector#1]
Hi sir. I'm graphics designer. I have studied your work. Your current logo is very good but I think a new simple logo will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.
Good luck...

![classinjector](https://user-images.githubusercontent.com/36432269/41440655-6c680680-7040-11e8-8d08-bfa51ebfd3cd.png)

Best regard
Famil

**Comment by tmurakami** [comment]
Hi Famil,

Thank you, they are pretty cool!
However, unfortunately, I am not looking for a logo.
I appreciate your valuable efforts!
